CREATE TABLE IF NOT EXISTS strategy_config (
  strategy_code varchar(30) NOT NULL,
  config_group varchar(50) NOT NULL,
  config_key varchar(100) NOT NULL,
  config_value varchar(100) NOT NULL,
  value_type varchar(20) NOT NULL,
  description varchar(500) DEFAULT NULL,
  enabled tinyint(1) NOT NULL DEFAULT 1,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (strategy_code, config_key),
  KEY idx_group (config_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO strategy_config (strategy_code,config_group,config_key,config_value,value_type,description) VALUES
('S2560','A','ma_price_period','25','int','价格均线周期'),
('S2560','A','vol_short_period','5','int','短期均量周期'),
('S2560','A','vol_long_period','60','int','长期均量周期'),
('S2560','A','ma_slope_medium_threshold','0.0','double','中性趋势斜率阈值'),
('S2560','B','pullback_threshold_pct','2.0','double','回踩MA25最大允许偏差'),
('S2560','C','min_volume_ratio','1.0','double','量能最低倍数'),
('S2560','C','resistance_threshold','0.95','double','接近压力位阈值'),
('S2560','C','breakout_threshold','1.0','double','突破前高阈值'),
('S2560','C','atr_weak_ratio','0.85','double','ATR活跃最低比例'),
('S2560','D','signal_cooldown_days','3','int','同标信号冷却天数');

CREATE TABLE IF NOT EXISTS analysis_batch (
  batch_id bigint NOT NULL,
  batch_name varchar(100) DEFAULT NULL,
  run_time datetime NOT NULL,
  data_source varchar(20) DEFAULT NULL,
  strategy_code varchar(30) NOT NULL,
  strategy_version varchar(30) NOT NULL,
  param_snapshot json DEFAULT NULL,
  status varchar(20) NOT NULL,
  message varchar(1000) DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (batch_id),
  KEY idx_run_time (run_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS minute_kline_period (
  code varchar(20) NOT NULL,
  date int NOT NULL,
  period varchar(10) NOT NULL DEFAULT '5m',
  source varchar(20) NOT NULL,
  open double DEFAULT NULL,
  high double DEFAULT NULL,
  low double DEFAULT NULL,
  close double DEFAULT NULL,
  volume double DEFAULT NULL,
  amount double DEFAULT NULL,
  PRIMARY KEY (code,date,period,source),
  KEY idx_date_period (date,period)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS technical_indicator (
  code varchar(20) NOT NULL,
  period varchar(10) NOT NULL,
  date int NOT NULL,
  source varchar(20) NOT NULL,
  stock_status varchar(20) DEFAULT 'NORMAL',
  is_st tinyint(1) NOT NULL DEFAULT 0,
  ma25 double DEFAULT NULL,
  ma60 double DEFAULT NULL,
  ma200 double DEFAULT NULL,
  ma25_slope_3 double DEFAULT NULL,
  ma60_slope_3 double DEFAULT NULL,
  atr14 double DEFAULT NULL,
  atr20_avg double DEFAULT NULL,
  vol_ma5 double DEFAULT NULL,
  vol_ma60 double DEFAULT NULL,
  vol_ratio double DEFAULT NULL,
  vol_ma5_cross_vol_ma60 tinyint(1) DEFAULT NULL,
  price_ma25_deviation_pct double DEFAULT NULL,
  high_20 double DEFAULT NULL,
  low_20 double DEFAULT NULL,
  low_30 double DEFAULT NULL,
  resistance_level double DEFAULT NULL,
  is_abnormal_bar tinyint(1) DEFAULT 0,
  data_quality_status varchar(30) DEFAULT 'normal',
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (code,period,date,source),
  KEY idx_period_date (period,date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS structure_2560_analysis (
  id bigint NOT NULL AUTO_INCREMENT,
  signal_uid varchar(32) NOT NULL,
  batch_id bigint NOT NULL,
  strategy_code varchar(30) NOT NULL DEFAULT 'S2560',
  strategy_version varchar(30) NOT NULL,
  code varchar(20) NOT NULL,
  name varchar(100) DEFAULT NULL,
  signal_time int NOT NULL,
  signal_period varchar(10) NOT NULL DEFAULT '30m',
  price double DEFAULT NULL,
  source varchar(20) DEFAULT NULL,
  stock_status varchar(20) DEFAULT 'NORMAL',
  has_2560_signal tinyint(1) DEFAULT NULL,
  price_near_ma25 tinyint(1) DEFAULT NULL,
  ma25_slope_ok tinyint(1) DEFAULT NULL,
  volume_structure_ok tinyint(1) DEFAULT NULL,
  abnormal_filter_ok tinyint(1) DEFAULT NULL,
  trend_price_ok tinyint(1) DEFAULT NULL,
  trend_slope_ok tinyint(1) DEFAULT NULL,
  volatility_ok tinyint(1) DEFAULT NULL,
  breakout_ok tinyint(1) DEFAULT NULL,
  volume_ok tinyint(1) DEFAULT NULL,
  near_resistance tinyint(1) DEFAULT NULL,
  pullback_ok tinyint(1) DEFAULT NULL,
  bullish_confirm tinyint(1) DEFAULT NULL,
  structure_status varchar(20) DEFAULT NULL,
  strength_score_raw double DEFAULT NULL,
  missing_tags varchar(500) DEFAULT NULL,
  missing_tag_count int DEFAULT 0,
  explain_text varchar(1000) DEFAULT NULL,
  data_quality_status varchar(30) DEFAULT 'normal',
  is_duplicate_signal tinyint(1) DEFAULT 0,
  selected_signal tinyint(1) DEFAULT 1,
  future_return_1d double DEFAULT NULL,
  future_return_3d double DEFAULT NULL,
  future_return_5d double DEFAULT NULL,
  future_max_gain_5d double DEFAULT NULL,
  future_max_drawdown_5d double DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_signal_uid (signal_uid),
  KEY idx_batch_status (batch_id,structure_status),
  KEY idx_signal_time (signal_time),
  KEY idx_code_time (code,signal_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS structure_2560_tag_detail (
  id bigint NOT NULL AUTO_INCREMENT,
  analysis_id bigint NOT NULL,
  batch_id bigint NOT NULL,
  code varchar(20) NOT NULL,
  signal_time int NOT NULL,
  tag_code varchar(50) NOT NULL,
  tag_name varchar(100) NOT NULL,
  tag_type varchar(50) DEFAULT 'negative',
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_analysis_id (analysis_id),
  KEY idx_tag_time (tag_code,signal_time),
  KEY idx_batch_tag (batch_id,tag_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS structure_2560_statistics (
  id bigint NOT NULL AUTO_INCREMENT,
  batch_id bigint NOT NULL,
  stat_date int NOT NULL,
  stat_type varchar(50) NOT NULL,
  group_key varchar(100) NOT NULL,
  sample_count int NOT NULL DEFAULT 0,
  avg_return_1d double DEFAULT NULL,
  avg_return_3d double DEFAULT NULL,
  avg_return_5d double DEFAULT NULL,
  win_rate_1d double DEFAULT NULL,
  win_rate_3d double DEFAULT NULL,
  win_rate_5d double DEFAULT NULL,
  avg_max_gain_5d double DEFAULT NULL,
  avg_max_drawdown_5d double DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_batch_date_type (batch_id,stat_date,stat_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS data_quality_check (
  id bigint NOT NULL AUTO_INCREMENT,
  check_date int NOT NULL,
  source varchar(20) NOT NULL,
  period varchar(10) NOT NULL,
  total_symbols int DEFAULT 0,
  available_symbols int DEFAULT 0,
  missing_symbols int DEFAULT 0,
  abnormal_bar_count int DEFAULT 0,
  status varchar(30) NOT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_date_period (check_date,period)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
